version: '3'
services:
  mongo:
    image: mongo
    container_name: lacevista-mongo
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: lacevista-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/LaceVista
